services: 

    # docker run -it --rm \
    #   --network front \
    #   bitnami/kafka:latest kafka-topics.sh --list  --bootstrap-server kafka.example.com:9092

  envoy-kafka-frontend: 
    image: envoyproxy/envoy:v1.28-latest
    hostname: envoy
    ports: 
      - "10000:10000"
    volumes: 
      - ./envoy-kafka-client.yaml:/etc/envoy/envoy.yaml
      - ./certs:/certs/
    depends_on: 
      - envoy-kafka-backend
    environment:
      - loglevel=info
    networks:
      front:
        aliases:
          - kafka.example.com
      envoymesh:
        aliases:
          - proxy-kafka-frontend.example.com

  envoy-kafka-backend: 
    image: envoyproxy/envoy:v1.28-latest
    hostname: envoy
    volumes: 
      - ./envoy-kafka.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
      - ./certs:/certs/
    depends_on: 
      - kafka
    environment:
      - loglevel=info
    networks: 
      kafka-int:
      envoymesh: 
        aliases:
          - proxy-kafka-backend.example.com

  kafka: 
    image: 'bitnami/kafka:latest'
    ports: 
      - 9094:9094
    environment: 
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka.example.com:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # - KAFKA_CLIENT_USERS=track
      # - KAFKA_CLIENT_PASSWORDS=track
    networks: 
      kafka-int:

networks:
  front:
    name: front
  envoymesh: 
    name: envoymesh
  kafka-int: 
    name: kafka-int
 